"""Initial schema

Revision ID: 662c5ce6b7fc
Revises: 
Create Date: 2026-07-05 03:37:46.571411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '662c5ce6b7fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baa_registry',
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('baa_document_url', sa.String(), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('phi_categories', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('subprocessors', sa.JSON(), nullable=True),
    sa.Column('ai_training_prohibited', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('status_code', sa.String(length=10), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_idempotency_key_tenant', 'idempotency_keys', ['key', 'tenant_id'], unique=True)
    op.create_index(op.f('ix_idempotency_keys_id'), 'idempotency_keys', ['id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_id'), 'outbox_events', ['id'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_events_tenant_id'), 'outbox_events', ['tenant_id'], unique=False)
    op.create_table('slot_locks',
    sa.Column('slot_key', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('locked_by_call_id', sa.String(), nullable=False),
    sa.Column('locked_by_ip', postgresql.INET(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('slot_key')
    )
    op.create_table('tenants',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('business_type', sa.String(), nullable=True),
    sa.Column('telnyx_did', sa.String(), nullable=True),
    sa.Column('retell_agent_id', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('security_officer_email', sa.String(), nullable=False),
    sa.Column('owner_email', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('telnyx_did')
    )
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_backup_codes', sa.Text(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_tenant_email', 'users', ['email'], unique=False)
    op.create_table('incident_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('incident_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('detected_by', sa.String(), nullable=True),
    sa.Column('affected_patient_count', sa.Integer(), nullable=False),
    sa.Column('phi_encrypted_at_time', sa.Boolean(), nullable=False),
    sa.Column('hhs_notification_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hhs_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_notification_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patients_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('phone_hash', sa.String(), nullable=False),
    sa.Column('phone_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('full_name_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('dob_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('is_existing_patient', sa.Boolean(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('total_revenue_cents', sa.Integer(), nullable=False),
    sa.Column('churn_risk_score', sa.Float(), nullable=True),
    sa.Column('last_visit_date', sa.Date(), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('data_access_level', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patient_last_visit', 'patients', ['last_visit_date'], unique=False)
    op.create_index('idx_patient_phone', 'patients', ['phone_hash'], unique=False)
    op.create_index(op.f('ix_patients_phone_hash'), 'patients', ['phone_hash'], unique=False)
    op.create_table('providers',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('is_accepting_patients', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provider_tenant_accepting', 'providers', ['is_accepting_patients'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('assessment_notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('clinic_name', sa.String(length=255), nullable=True),
    sa.Column('clinic_phone', sa.String(length=30), nullable=True),
    sa.Column('clinic_address', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('business_hours', sa.JSON(), nullable=True),
    sa.Column('providers', sa.JSON(), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('faq_entries', sa.JSON(), nullable=True),
    sa.Column('ai_persona', sa.JSON(), nullable=True),
    sa.Column('ai_persona_prompt', sa.String(), nullable=True),
    sa.Column('transfer_number', sa.String(length=30), nullable=True),
    sa.Column('sms_opt_out_list', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('training_completions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('appointments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('slot_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('booked_by', sa.String(), nullable=False),
    sa.Column('booked_via_call_id', sa.String(), nullable=True),
    sa.Column('confirmation_code', sa.String(), nullable=True),
    sa.Column('sms_confirmed', sa.Boolean(), nullable=False),
    sa.Column('reminder_24h_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_2h_sent', sa.Boolean(), nullable=False),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rescheduled_from_id', sa.UUID(), nullable=True),
    sa.Column('deleted_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appt_tenant_code', 'appointments', ['confirmation_code'], unique=True)
    op.create_index('idx_appt_tenant_patient', 'appointments', ['patient_id'], unique=False)
    op.create_index('idx_appt_tenant_provider_slot', 'appointments', ['provider_id', 'slot_start'], unique=False)
    op.create_index('idx_appt_tenant_slot_active', 'appointments', ['slot_start', 'status'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('call_logs',
    sa.Column('retell_call_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('caller_phone_hash', sa.String(), nullable=True),
    sa.Column('call_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('tools_invoked', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tools_results', sa.JSON(), nullable=True),
    sa.Column('transcript_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('recording_purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recording_purge_scheduled', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transfer_reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retell_call_id')
    )
    op.create_index('idx_calllog_purge_pending', 'call_logs', ['recording_purge_scheduled'], unique=False, postgresql_where=sa.text('recording_url IS NOT NULL'))
    op.create_index('idx_calllog_tenant_date', 'call_logs', ['created_at'], unique=False)
    op.create_index('idx_calllog_tenant_patient', 'call_logs', ['patient_id'], unique=False)
    op.create_table('waitlist',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('preferred_days', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('preferred_day', sa.String(), nullable=True),
    sa.Column('preferred_time_range', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booked_from_waitlist', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_notes',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('call_log_id', sa.UUID(), nullable=True),
    sa.Column('authored_by', sa.String(), nullable=False),
    sa.Column('note_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('note_hash', sa.String(), nullable=False),
    sa.Column('access_level', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['call_log_id'], ['call_logs.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clinicalnote_tenant_patient', 'clinical_notes', ['patient_id', 'created_at'], unique=False)
    op.create_table('sms_logs',
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('telnyx_message_id', sa.String(), nullable=True),
    sa.Column('sms_type', sa.String(), nullable=True),
    sa.Column('message_body_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('parsed_intent', sa.String(), nullable=True),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telnyx_message_id')
    )
    op.create_index('idx_smslog_tenant_patient', 'sms_logs', ['patient_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_smslog_tenant_patient', table_name='sms_logs')
    op.drop_table('sms_logs')
    op.drop_index('idx_clinicalnote_tenant_patient', table_name='clinical_notes')
    op.drop_table('clinical_notes')
    op.drop_table('waitlist')
    op.drop_index('idx_calllog_tenant_patient', table_name='call_logs')
    op.drop_index('idx_calllog_tenant_date', table_name='call_logs')
    op.drop_index('idx_calllog_purge_pending', table_name='call_logs', postgresql_where=sa.text('recording_url IS NOT NULL'))
    op.drop_table('call_logs')
    op.drop_index('idx_appt_tenant_slot_active', table_name='appointments', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('idx_appt_tenant_provider_slot', table_name='appointments')
    op.drop_index('idx_appt_tenant_patient', table_name='appointments')
    op.drop_index('idx_appt_tenant_code', table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('user_sessions')
    op.drop_table('training_completions')
    op.drop_table('tenant_settings')
    op.drop_table('risk_assessments')
    op.drop_index('idx_provider_tenant_accepting', table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_patients_phone_hash'), table_name='patients')
    op.drop_index('idx_patient_phone', table_name='patients')
    op.drop_index('idx_patient_last_visit', table_name='patients')
    op.drop_table('patients')
    op.drop_table('incident_logs')
    op.drop_index('idx_user_tenant_email', table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('slot_locks')
    op.drop_index(op.f('ix_outbox_events_tenant_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_idempotency_keys_id'), table_name='idempotency_keys')
    op.drop_index('ix_idempotency_key_tenant', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_table('baa_registry')
    # ### end Alembic commands ###
