"""Add tenant_id back

Revision ID: ca568d2a24d8
Revises: 662c5ce6b7fc
Create Date: 2026-07-05 07:16:10.284382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca568d2a24d8'
down_revision: Union[str, None] = '662c5ce6b7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'tenants', ['tenant_id'], ['id'])
    op.add_column('baa_registry', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'baa_registry', 'tenants', ['tenant_id'], ['id'])
    op.add_column('call_logs', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'call_logs', 'tenants', ['tenant_id'], ['id'])
    op.add_column('clinical_notes', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'clinical_notes', 'tenants', ['tenant_id'], ['id'])
    op.add_column('patients', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'patients', 'tenants', ['tenant_id'], ['id'])
    op.add_column('providers', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'providers', 'tenants', ['tenant_id'], ['id'])
    op.add_column('sms_logs', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'sms_logs', 'tenants', ['tenant_id'], ['id'])
    op.add_column('training_completions', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'training_completions', 'tenants', ['tenant_id'], ['id'])
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    op.add_column('waitlist', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'waitlist', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waitlist', type_='foreignkey')
    op.drop_column('waitlist', 'tenant_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(None, 'training_completions', type_='foreignkey')
    op.drop_column('training_completions', 'tenant_id')
    op.drop_constraint(None, 'sms_logs', type_='foreignkey')
    op.drop_column('sms_logs', 'tenant_id')
    op.drop_constraint(None, 'providers', type_='foreignkey')
    op.drop_column('providers', 'tenant_id')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'tenant_id')
    op.drop_constraint(None, 'clinical_notes', type_='foreignkey')
    op.drop_column('clinical_notes', 'tenant_id')
    op.drop_constraint(None, 'call_logs', type_='foreignkey')
    op.drop_column('call_logs', 'tenant_id')
    op.drop_constraint(None, 'baa_registry', type_='foreignkey')
    op.drop_column('baa_registry', 'tenant_id')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'tenant_id')
    # ### end Alembic commands ###
