"""fix_provider_foreign_keys

Revision ID: d0eab12a5c8b
Revises: ca568d2a24d8
Create Date: 2026-07-08 18:13:52.510527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0eab12a5c8b'
down_revision: Union[str, None] = 'ca568d2a24d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointments_provider_id_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'providers', ['provider_id'], ['id'])
    op.drop_constraint('waitlist_provider_id_fkey', 'waitlist', type_='foreignkey')
    op.create_foreign_key(None, 'waitlist', 'providers', ['provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waitlist', type_='foreignkey')
    op.create_foreign_key('waitlist_provider_id_fkey', 'waitlist', 'users', ['provider_id'], ['id'])
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_provider_id_fkey', 'appointments', 'users', ['provider_id'], ['id'])
    # ### end Alembic commands ###
