"""Initial audit schema

Revision ID: af00cef3d2d7
Revises: 
Create Date: 2026-07-05 03:39:58.532591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af00cef3d2d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_table', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('target_patient_id', sa.UUID(), nullable=True),
    sa.Column('ingress_ip', sa.String(length=45), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('fields_accessed', sa.JSON(), nullable=True),
    sa.Column('before_snapshot', sa.JSON(), nullable=True),
    sa.Column('after_snapshot', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('denial_reason', sa.String(length=500), nullable=True),
    sa.Column('is_high_sensitivity', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_sequence_number'), 'audit_logs', ['sequence_number'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_patient_id'), 'audit_logs', ['target_patient_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_logs_tenant_patient', 'audit_logs', ['target_patient_id'], unique=False)
    op.create_index('ix_audit_logs_tenant_seq', 'audit_logs', ['sequence_number'], unique=False)
    
    # ── Immutable Hash-Chain Trigger ─────────────────────────────
    # Create the function to prevent updates and deletes
    op.execute("""
    CREATE OR REPLACE FUNCTION prevent_audit_modifications()
    RETURNS TRIGGER AS $$
    BEGIN
        IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'Audit logs are immutable and cannot be deleted.';
        ELSIF TG_OP = 'UPDATE' THEN
            RAISE EXCEPTION 'Audit logs are immutable and cannot be updated.';
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    # Create the trigger to fire on UPDATE or DELETE
    op.execute("""
    CREATE TRIGGER trg_prevent_audit_modifications
    BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH ROW
    EXECUTE FUNCTION prevent_audit_modifications();
    """)

    # Create the function to enforce sequence_number and hash chaining
    op.execute("""
    CREATE OR REPLACE FUNCTION enforce_audit_hash_chain()
    RETURNS TRIGGER AS $$
    DECLARE
        last_row RECORD;
        expected_prev_hash VARCHAR(64);
        payload TEXT;
    BEGIN
        -- Find the absolute latest row based on sequence_number
        SELECT sequence_number, row_hash INTO last_row
        FROM audit_logs
        ORDER BY sequence_number DESC
        LIMIT 1;

        IF last_row IS NULL THEN
            -- Genesis row
            NEW.sequence_number := 1;
            expected_prev_hash := NULL;
        ELSE
            -- Subsequent rows
            NEW.sequence_number := last_row.sequence_number + 1;
            expected_prev_hash := last_row.row_hash;
        END IF;

        -- Enforce previous_hash matches the actual last row_hash
        IF NEW.previous_hash IS DISTINCT FROM expected_prev_hash THEN
            NEW.previous_hash := expected_prev_hash;
        END IF;

        -- Compute row_hash = SHA256(COALESCE(previous_hash, '') || id || action || actor_id || created_at)
        -- We use a standardized payload string to hash
        payload := COALESCE(NEW.previous_hash, '') ||
                   NEW.id::text ||
                   NEW.action ||
                   COALESCE(NEW.actor_id::text, '') ||
                   COALESCE(NEW.target_patient_id::text, '') ||
                   EXTRACT(EPOCH FROM NEW.created_at)::text;
        
        NEW.row_hash := encode(digest(payload, 'sha256'), 'hex');

        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    
    # Ensure pgcrypto is enabled in the database for the digest function
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")

    # Create the trigger for insert
    op.execute("""
    CREATE TRIGGER trg_enforce_audit_hash_chain
    BEFORE INSERT ON audit_logs
    FOR EACH ROW
    EXECUTE FUNCTION enforce_audit_hash_chain();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trg_enforce_audit_hash_chain ON audit_logs;")
    op.execute("DROP FUNCTION IF EXISTS enforce_audit_hash_chain();")
    op.execute("DROP TRIGGER IF EXISTS trg_prevent_audit_modifications ON audit_logs;")
    op.execute("DROP FUNCTION IF EXISTS prevent_audit_modifications();")
    op.drop_index('ix_audit_logs_tenant_seq', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_patient', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_patient_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_sequence_number'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
